### ISSUE TITLE
Feature Request: Hide/Unhide window

### ISSUE THREAD

**Issue by theseyan** [ziglibs/positron#2]
Hi, I would like to submit a feature request for hiding and un-hiding the webview window (not exiting it).
If possible, it would also be cool to be able to hide the status/title bar on top and have functions to minimize/maximize the window which would allow for a custom title bar made in HTML.

Awesome library, btw!

**Comment by ikskuh** [comment]
If you check out the original header, there's not much i can actually expose:

https://github.com/ziglibs/positron/blob/e8954dba1e5568313fb4a57f0a87404dd87f3e77/src/wv/webview.h#L37-L108

I guess for these features you have to either hack all three backends to support these features, but i'll keep `positron` a flat and simple wrapper around the [webview](https://github.com/webview/webview) library + an embedded web server for local loopback requests.

**Comment by theseyan** [comment]
Ah, I guess it's better to open this feature request in the upstream webview library then👍
